// ============================================================
// customers-seed.ts
// Auto-generated from data_cross_sell.csv (ASJ cross-sell DB)
// 49 representative records, stratified by segment x gender
// Source total: 6,902 active policy records
//
// HOW TO USE IN data.ts:
// 1. Copy the Customer interface and CUSTOMERS array below
// 2. Paste into src/lib/data.ts alongside PRODUCTS
// 3. Import CUSTOMERS wherever you need it, e.g. Customers.tsx:
//      import { CUSTOMERS } from '@/lib/data';
// ============================================================

export interface Customer {
  id: number;
  regSpaj: string;      // 10-char alphanumeric
  cif: string;          // 10-char alphanumeric
  policyNo: string;     // 12-char alphanumeric
  name: string;
  gender: 'male' | 'female';
  maritalStatus: 'married' | 'single' | 'widow' | 'widower';
  age: number;
  occupation: string;
  province: string;
  city: string;
  salaryBucket: string;
  segment: 'Top Customers' | 'High value Customer' | 'Medium Value Customer' | 'Low Value Customers' | 'Lost Customers';
  purchaseIntent: string;
  relationPolis: string;
  productId: number;    // references Product.id in PRODUCTS array
  productName: string;
  totalPremi: number;   // in IDR
  channel: 'Agency' | 'Bancassurance' | 'Syariah' | 'Digital';
  transactionDate: string;
}

export const CUSTOMERS: Customer[] = [
  {
    id: 1,
    regSpaj: 'UT6FIZHJMX',
    cif: '45RHQFZQMJ',
    policyNo: 'GZVL7GBXT6AQ',
    name: 'Elisa Sinaga',
    gender: 'female',
    maritalStatus: 'single',
    age: 28,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'KALIMANTAN BARAT',
    city: 'KOTA PONTIANAK',
    salaryBucket: '> 100 Juta - 150 Juta',
    segment: 'High value Customer',
    purchaseIntent: 'Investment',
    relationPolis: 'Diri Sendiri',
    productId: 2,
    productName: 'SIPASTI',
    totalPremi: 20000000,
    channel: 'Bancassurance',
    transactionDate: '9/4/2024',
  },
  {
    id: 2,
    regSpaj: 'LMUCOA9LCP',
    cif: 'YCM1725C1V',
    policyNo: 'L01BO0W7LG50',
    name: 'Putri Wijaya',
    gender: 'female',
    maritalStatus: 'married',
    age: 61,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'DKI JAKARTA',
    city: 'KOTA JAKARTA SELATAN',
    salaryBucket: '> 100 Juta - 150 Juta',
    segment: 'High value Customer',
    purchaseIntent: 'Protection',
    relationPolis: 'Diri Sendiri',
    productId: 2,
    productName: 'SIPASTI',
    totalPremi: 24000000,
    channel: 'Bancassurance',
    transactionDate: '9/30/2024',
  },
  {
    id: 3,
    regSpaj: '9CS4A2IS06',
    cif: 'SAC07J0NP7',
    policyNo: 'H3W6D0NOQ91U',
    name: 'Tania Simanjuntak',
    gender: 'female',
    maritalStatus: 'married',
    age: 51,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'BANTEN',
    city: 'KOTA TANGERANG SELATAN',
    salaryBucket: '> 100 Juta - 150 Juta',
    segment: 'High value Customer',
    purchaseIntent: 'Protection',
    relationPolis: 'Diri Sendiri',
    productId: 3,
    productName: 'SIMAS SCHOLARSHIP PROTECTION',
    totalPremi: 500000000,
    channel: 'Bancassurance',
    transactionDate: '8/21/2025',
  },
  {
    id: 4,
    regSpaj: 'TEL745CSF0',
    cif: '7S9EFVBREV',
    policyNo: 'VAHRCPYRD4Q9',
    name: 'Gita Siahaan',
    gender: 'female',
    maritalStatus: 'married',
    age: 42,
    occupation: 'Pedagang Grosir',
    province: 'BANGKA BELITUNG',
    city: 'BELITUNG',
    salaryBucket: '> 100 Juta - 150 Juta',
    segment: 'High value Customer',
    purchaseIntent: 'Retirement',
    relationPolis: 'Diri Sendiri',
    productId: 2,
    productName: 'SIPASTI',
    totalPremi: 12000000,
    channel: 'Bancassurance',
    transactionDate: '3/27/2025',
  },
  {
    id: 5,
    regSpaj: 'QDM2KON8U3',
    cif: 'F1ZZ81JCDY',
    policyNo: '31L7CRE7RIJ8',
    name: 'Fara Tobing',
    gender: 'female',
    maritalStatus: 'married',
    age: 49,
    occupation: 'Karyawan Swasta',
    province: 'DKI JAKARTA',
    city: 'KOTA JAKARTA PUSAT',
    salaryBucket: '> 250 Juta - 300 Juta',
    segment: 'High value Customer',
    purchaseIntent: 'Retirement',
    relationPolis: 'Diri Sendiri',
    productId: 3,
    productName: 'SIMAS SCHOLARSHIP PROTECTION',
    totalPremi: 500000000,
    channel: 'Bancassurance',
    transactionDate: '10/31/2025',
  },
  {
    id: 6,
    regSpaj: 'UD24DKRF4F',
    cif: 'TYZBLI4Z3Y',
    policyNo: '60IRQBCWDOU4',
    name: 'Hesti Nugraha',
    gender: 'female',
    maritalStatus: 'single',
    age: 23,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'JAWA TIMUR',
    city: 'KOTA SURABAYA',
    salaryBucket: '> 250 Juta - 300 Juta',
    segment: 'High value Customer',
    purchaseIntent: 'Protection',
    relationPolis: 'Diri Sendiri',
    productId: 3,
    productName: 'SIMAS SCHOLARSHIP PROTECTION',
    totalPremi: 250000000,
    channel: 'Bancassurance',
    transactionDate: '7/4/2025',
  },
  {
    id: 7,
    regSpaj: 'ZJ82ZQYJM3',
    cif: 'N3L9H7H6WK',
    policyNo: 'Q6JRPACQ5XZ9',
    name: 'Gilang Simanjuntak',
    gender: 'male',
    maritalStatus: 'married',
    age: 34,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'JAMBI',
    city: 'KOTA JAMBI',
    salaryBucket: '> 100 Juta - 150 Juta',
    segment: 'High value Customer',
    purchaseIntent: 'Protection',
    relationPolis: 'Diri Sendiri',
    productId: 3,
    productName: 'SIMAS SCHOLARSHIP PROTECTION',
    totalPremi: 250000000,
    channel: 'Bancassurance',
    transactionDate: '9/23/2025',
  },
  {
    id: 8,
    regSpaj: 'A9LBPREC5Y',
    cif: 'TOBXI9GZKP',
    policyNo: 'D639WRNFMB5F',
    name: 'Sandi Tobing',
    gender: 'male',
    maritalStatus: 'married',
    age: 59,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'KALIMANTAN BARAT',
    city: 'KOTA PONTIANAK',
    salaryBucket: '> 1 Milyar',
    segment: 'High value Customer',
    purchaseIntent: 'Protection',
    relationPolis: 'Diri Sendiri',
    productId: 3,
    productName: 'SIMAS SCHOLARSHIP PROTECTION',
    totalPremi: 1000000000,
    channel: 'Bancassurance',
    transactionDate: '8/4/2025',
  },
  {
    id: 9,
    regSpaj: 'GFBCHZ6PUF',
    cif: 'B8Z5NICMLE',
    policyNo: 'NIFGNPGR8P8N',
    name: 'Irfan Wijaya',
    gender: 'male',
    maritalStatus: 'married',
    age: 35,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'JAWA TENGAH',
    city: 'KOTA SEMARANG',
    salaryBucket: '> 100 Juta - 150 Juta',
    segment: 'High value Customer',
    purchaseIntent: 'Investment',
    relationPolis: 'Diri Sendiri',
    productId: 2,
    productName: 'SIPASTI',
    totalPremi: 30000000,
    channel: 'Bancassurance',
    transactionDate: '7/26/2023',
  },
  {
    id: 10,
    regSpaj: '7Y6CLGRR4C',
    cif: 'TIDSSJ2W6B',
    policyNo: 'GTIBLSHABBBX',
    name: 'Fajar Suharto',
    gender: 'male',
    maritalStatus: 'married',
    age: 54,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'KALIMANTAN TIMUR',
    city: 'KOTA BALIKPAPAN',
    salaryBucket: '> 1 Milyar',
    segment: 'High value Customer',
    purchaseIntent: 'Family Protection',
    relationPolis: 'Diri Sendiri',
    productId: 2,
    productName: 'SIPASTI',
    totalPremi: 91620000,
    channel: 'Bancassurance',
    transactionDate: '8/24/2023',
  },
  {
    id: 11,
    regSpaj: 'K8OQ5GLIGY',
    cif: 'D5U2NKMBGF',
    policyNo: 'UBDEL4T3XB53',
    name: 'Gilang Tambunan',
    gender: 'male',
    maritalStatus: 'married',
    age: 44,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'LAMPUNG',
    city: 'KOTA BANDAR LAMPUNG',
    salaryBucket: '> 500 Juta - 1 Milyar',
    segment: 'High value Customer',
    purchaseIntent: 'Education',
    relationPolis: 'Orang tua kandung',
    productId: 11,
    productName: 'SIJI SMART KID',
    totalPremi: 29626000,
    channel: 'Bancassurance',
    transactionDate: '6/9/2023',
  },
  {
    id: 12,
    regSpaj: 'O5W5D8QBA3',
    cif: '88AR3UDHAD',
    policyNo: 'ZRWRJT67E3ZO',
    name: 'Lukman Siregar',
    gender: 'male',
    maritalStatus: 'married',
    age: 40,
    occupation: 'Karyawan Swasta',
    province: 'DKI JAKARTA',
    city: 'KOTA JAKARTA UTARA',
    salaryBucket: '> 250 Juta - 300 Juta',
    segment: 'High value Customer',
    purchaseIntent: 'Protection',
    relationPolis: 'Diri Sendiri',
    productId: 3,
    productName: 'SIMAS SCHOLARSHIP PROTECTION',
    totalPremi: 250000000,
    channel: 'Bancassurance',
    transactionDate: '9/23/2025',
  },
  {
    id: 13,
    regSpaj: '9551AXTO8D',
    cif: 'QRYS5I84W8',
    policyNo: 'E36LT7IS7VYN',
    name: 'Yesi Hidayat',
    gender: 'female',
    maritalStatus: 'married',
    age: 33,
    occupation: 'Pegawai Negri Sipil',
    province: '',
    city: '',
    salaryBucket: '0 - 50 Juta',
    segment: 'Lost Customers',
    purchaseIntent: 'Education',
    relationPolis: 'Diri Sendiri',
    productId: 14,
    productName: 'KADO JENIUS - MKJ5',
    totalPremi: 7014000,
    channel: 'Agency',
    transactionDate: '10/15/2015',
  },
  {
    id: 14,
    regSpaj: 'TKXZ0RW9DK',
    cif: 'ZFCCFWZH5N',
    policyNo: 'T6CND2UZR4Y8',
    name: 'Rini Rahmadi',
    gender: 'female',
    maritalStatus: 'married',
    age: 44,
    occupation: 'Wiraswasta/Wirausaha',
    province: '',
    city: '',
    salaryBucket: '0 - 50 Juta',
    segment: 'Low Value Customers',
    purchaseIntent: 'Investment',
    relationPolis: 'Diri Sendiri',
    productId: 6,
    productName: 'ASURANSI MAXI PRO',
    totalPremi: 350000,
    channel: 'Agency',
    transactionDate: '7/30/2015',
  },
  {
    id: 15,
    regSpaj: 'YEKZYZ7W2G',
    cif: 'MR2ZH5T1G1',
    policyNo: 'FA2QBAM7P9FO',
    name: 'Putri Wibowo',
    gender: 'female',
    maritalStatus: 'single',
    age: 37,
    occupation: 'Karyawan Swasta',
    province: '',
    city: '',
    salaryBucket: '0 - 50 Juta',
    segment: 'Low Value Customers',
    purchaseIntent: 'Investment',
    relationPolis: 'Diri Sendiri',
    productId: 4,
    productName: 'SIMAS LINK TASYAKUR SYARIAH',
    totalPremi: 250000,
    channel: 'Syariah',
    transactionDate: '8/31/2015',
  },
  {
    id: 16,
    regSpaj: 'B5TNN41WC6',
    cif: 'CPIBW0BVXG',
    policyNo: 'WPYZX0RCW3UU',
    name: 'Rini Wibowo',
    gender: 'female',
    maritalStatus: 'single',
    age: 34,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'SUMATERA UTARA',
    city: 'KOTA MEDAN',
    salaryBucket: '0 - 50 Juta',
    segment: 'Low Value Customers',
    purchaseIntent: 'Health',
    relationPolis: 'Diri Sendiri',
    productId: 6,
    productName: 'ASURANSI MAXI PRO',
    totalPremi: 400000,
    channel: 'Agency',
    transactionDate: '3/14/2016',
  },
  {
    id: 17,
    regSpaj: 'MQYBXPFYJL',
    cif: 'YYAHU8YJ50',
    policyNo: 'AOPW6OY1FX97',
    name: 'Elisa Tambunan',
    gender: 'female',
    maritalStatus: 'married',
    age: 33,
    occupation: 'Pegawai Bank',
    province: 'DKI JAKARTA',
    city: 'KOTA JAKARTA BARAT',
    salaryBucket: '0 - 50 Juta',
    segment: 'Low Value Customers',
    purchaseIntent: 'Family Protection',
    relationPolis: 'Diri Sendiri',
    productId: 9,
    productName: 'DECREASING TERM LIFE',
    totalPremi: 181650,
    channel: 'Agency',
    transactionDate: '12/30/2021',
  },
  {
    id: 18,
    regSpaj: '4AQBI4FO7P',
    cif: 'QS60A4MBF3',
    policyNo: 'TBACCRY5LRBJ',
    name: 'Sinta Harahap',
    gender: 'female',
    maritalStatus: 'married',
    age: 39,
    occupation: 'Other',
    province: '',
    city: '',
    salaryBucket: '0 - 50 Juta',
    segment: 'Low Value Customers',
    purchaseIntent: 'Investment',
    relationPolis: 'Orang tua kandung',
    productId: 12,
    productName: 'MEGA MAXI PLAN',
    totalPremi: 9450000,
    channel: 'Agency',
    transactionDate: '10/13/2014',
  },
  {
    id: 19,
    regSpaj: 'DZOJD5F0GF',
    cif: 'U78SBZ1FW9',
    policyNo: 'SW5N23FH2B44',
    name: 'Clara Manurung',
    gender: 'female',
    maritalStatus: 'married',
    age: 40,
    occupation: 'Wiraswasta/Wirausaha',
    province: '',
    city: '',
    salaryBucket: '> 100 Juta - 150 Juta',
    segment: 'Low Value Customers',
    purchaseIntent: 'Education',
    relationPolis: 'Diri Sendiri',
    productId: 4,
    productName: 'SIMAS LINK TASYAKUR SYARIAH',
    totalPremi: 300000,
    channel: 'Syariah',
    transactionDate: '9/17/2015',
  },
  {
    id: 20,
    regSpaj: 'MNTXBJ31DN',
    cif: 'ZYR3L3BCKA',
    policyNo: 'D6TVGSZGEUR8',
    name: 'Yusuf Suharto',
    gender: 'male',
    maritalStatus: 'single',
    age: 34,
    occupation: 'Wiraswasta/Wirausaha',
    province: '',
    city: '',
    salaryBucket: '0 - 50 Juta',
    segment: 'Low Value Customers',
    purchaseIntent: 'Investment',
    relationPolis: 'Diri Sendiri',
    productId: 4,
    productName: 'SIMAS LINK TASYAKUR SYARIAH',
    totalPremi: 600000,
    channel: 'Syariah',
    transactionDate: '7/31/2015',
  },
  {
    id: 21,
    regSpaj: 'QVJQS4CPTR',
    cif: 'ZDP6CHCV8W',
    policyNo: 'ICQVL5ELZQTM',
    name: 'Made Situmorang',
    gender: 'male',
    maritalStatus: 'single',
    age: 33,
    occupation: 'Karyawan Swasta',
    province: '',
    city: '',
    salaryBucket: '0 - 50 Juta',
    segment: 'Low Value Customers',
    purchaseIntent: 'Investment',
    relationPolis: 'Diri Sendiri',
    productId: 4,
    productName: 'SIMAS LINK TASYAKUR SYARIAH',
    totalPremi: 400000,
    channel: 'Syariah',
    transactionDate: '9/30/2015',
  },
  {
    id: 22,
    regSpaj: 'YAZPQV6UU2',
    cif: '4FWKYZU4KN',
    policyNo: '7P98WU1JLB3W',
    name: 'Gilang Pardede',
    gender: 'male',
    maritalStatus: 'married',
    age: 49,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'SUMATERA UTARA',
    city: 'KOTA MEDAN',
    salaryBucket: '0 - 50 Juta',
    segment: 'Low Value Customers',
    purchaseIntent: 'Family Protection',
    relationPolis: 'Diri Sendiri',
    productId: 6,
    productName: 'ASURANSI MAXI PRO',
    totalPremi: 350000,
    channel: 'Agency',
    transactionDate: '6/16/2015',
  },
  {
    id: 23,
    regSpaj: 'B8H7CYQBWK',
    cif: 'TGCJSTBH3V',
    policyNo: 'B0ZW6HIV7ML6',
    name: 'Dani Hartono',
    gender: 'male',
    maritalStatus: 'single',
    age: 31,
    occupation: 'Karyawan Swasta',
    province: 'SUMATERA UTARA',
    city: 'KOTA MEDAN',
    salaryBucket: '> 50 Juta - 100 Juta',
    segment: 'Low Value Customers',
    purchaseIntent: 'Health',
    relationPolis: 'Diri Sendiri',
    productId: 6,
    productName: 'ASURANSI MAXI PRO',
    totalPremi: 350000,
    channel: 'Agency',
    transactionDate: '10/8/2015',
  },
  {
    id: 24,
    regSpaj: 'RL9QFCPK7P',
    cif: 'O841F6IM0C',
    policyNo: '51J3JL8DRYDH',
    name: 'Yoga Lubis',
    gender: 'male',
    maritalStatus: 'married',
    age: 47,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'SUMATERA BARAT',
    city: 'KOTA PADANG',
    salaryBucket: '0 - 50 Juta',
    segment: 'Low Value Customers',
    purchaseIntent: 'Family Protection',
    relationPolis: 'Diri Sendiri',
    productId: 9,
    productName: 'DECREASING TERM LIFE',
    totalPremi: 98100,
    channel: 'Agency',
    transactionDate: '10/18/2019',
  },
  {
    id: 25,
    regSpaj: '1QAYTTZ9UU',
    cif: '3G7HCJOTMB',
    policyNo: 'W5RVIT4HQ3OZ',
    name: 'Bambang Panjaitan',
    gender: 'male',
    maritalStatus: 'single',
    age: 37,
    occupation: 'Karyawan Swasta',
    province: 'DKI JAKARTA',
    city: 'KOTA JAKARTA PUSAT',
    salaryBucket: '> 50 Juta - 100 Juta',
    segment: 'Low Value Customers',
    purchaseIntent: 'Investment',
    relationPolis: 'Diri Sendiri',
    productId: 10,
    productName: 'OPTIMA PLUS',
    totalPremi: 250000,
    channel: 'Bancassurance',
    transactionDate: '5/27/2015',
  },
  {
    id: 26,
    regSpaj: 'SQ7TFS2E2F',
    cif: 'ZTF8RT7X9Z',
    policyNo: '57OCBPMSXMHG',
    name: 'Vina Wibowo',
    gender: 'female',
    maritalStatus: 'married',
    age: 29,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'JAWA TIMUR',
    city: 'KOTA SURABAYA',
    salaryBucket: '> 100 Juta - 150 Juta',
    segment: 'Medium Value Customer',
    purchaseIntent: 'Family Protection',
    relationPolis: 'Diri Sendiri',
    productId: 1,
    productName: 'SIMAS JIWA LEGACY',
    totalPremi: 2123820,
    channel: 'Agency',
    transactionDate: '11/9/2020',
  },
  {
    id: 27,
    regSpaj: 'YLX2CRL39Y',
    cif: '3XFVIZXHZA',
    policyNo: 'UU9F645HZI8D',
    name: 'Yuni Situmorang',
    gender: 'female',
    maritalStatus: 'single',
    age: 29,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'JAWA TIMUR',
    city: 'KOTA SURABAYA',
    salaryBucket: '> 100 Juta - 150 Juta',
    segment: 'Medium Value Customer',
    purchaseIntent: 'Family Protection',
    relationPolis: 'Diri Sendiri',
    productId: 1,
    productName: 'SIMAS JIWA LEGACY',
    totalPremi: 12750000,
    channel: 'Agency',
    transactionDate: '7/30/2020',
  },
  {
    id: 28,
    regSpaj: 'YQGYIW59OD',
    cif: 'RIOZMMP8DM',
    policyNo: '1OI3K82WV7O6',
    name: 'Intan Saragih',
    gender: 'female',
    maritalStatus: 'married',
    age: 54,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'JAWA TIMUR',
    city: 'KOTA SURABAYA',
    salaryBucket: '> 250 Juta - 300 Juta',
    segment: 'Medium Value Customer',
    purchaseIntent: 'Investment',
    relationPolis: 'Diri Sendiri',
    productId: 1,
    productName: 'SIMAS JIWA LEGACY',
    totalPremi: 34258000,
    channel: 'Agency',
    transactionDate: '10/31/2019',
  },
  {
    id: 29,
    regSpaj: '3I6WTL0OC7',
    cif: 'FNZ21BQUGZ',
    policyNo: 'XS44DUAWZOWR',
    name: 'Sri Nainggolan',
    gender: 'female',
    maritalStatus: 'single',
    age: 33,
    occupation: 'Karyawan Swasta',
    province: 'JAWA TIMUR',
    city: 'KOTA SURABAYA',
    salaryBucket: '> 100 Juta - 150 Juta',
    segment: 'Medium Value Customer',
    purchaseIntent: 'Investment',
    relationPolis: 'Diri Sendiri',
    productId: 1,
    productName: 'SIMAS JIWA LEGACY',
    totalPremi: 8253600,
    channel: 'Agency',
    transactionDate: '6/28/2019',
  },
  {
    id: 30,
    regSpaj: 'X8UBES81DE',
    cif: 'CWGFYUEGTH',
    policyNo: 'WOAI6NWDZ4RG',
    name: 'Farah Rajagukguk',
    gender: 'female',
    maritalStatus: 'married',
    age: 44,
    occupation: 'Ibu Rumah Tangga',
    province: 'KALIMANTAN BARAT',
    city: 'KOTA PONTIANAK',
    salaryBucket: '0 - 50 Juta',
    segment: 'Medium Value Customer',
    purchaseIntent: 'Education',
    relationPolis: 'Orang tua kandung',
    productId: 11,
    productName: 'SIJI SMART KID',
    totalPremi: 68404000,
    channel: 'Bancassurance',
    transactionDate: '3/14/2022',
  },
  {
    id: 31,
    regSpaj: 'U8KY6E1YMS',
    cif: 'J6X87XPR35',
    policyNo: 'FK0UBHTUT8TR',
    name: 'Tania Setiawan',
    gender: 'female',
    maritalStatus: 'married',
    age: 59,
    occupation: 'Pegawai Negri Sipil',
    province: 'DKI JAKARTA',
    city: 'KOTA JAKARTA PUSAT',
    salaryBucket: '0 - 50 Juta',
    segment: 'Medium Value Customer',
    purchaseIntent: 'Retirement',
    relationPolis: 'Diri Sendiri',
    productId: 2,
    productName: 'SIPASTI',
    totalPremi: 10000000,
    channel: 'Bancassurance',
    transactionDate: '2/14/2023',
  },
  {
    id: 32,
    regSpaj: 'IU321Z3WKW',
    cif: 'M147BQKVNQ',
    policyNo: 'TFJX1X19RA1U',
    name: 'Joko Prasetyo',
    gender: 'male',
    maritalStatus: 'married',
    age: 57,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'SUMATERA UTARA',
    city: 'KOTA MEDAN',
    salaryBucket: '> 100 Juta - 150 Juta',
    segment: 'Medium Value Customer',
    purchaseIntent: 'Family Protection',
    relationPolis: 'Diri Sendiri',
    productId: 6,
    productName: 'ASURANSI MAXI PRO',
    totalPremi: 800000,
    channel: 'Agency',
    transactionDate: '8/13/2015',
  },
  {
    id: 33,
    regSpaj: 'XWNRSNIMUX',
    cif: 'K0KNE5YSO0',
    policyNo: 'RABY4KY6MGB2',
    name: 'Rafi Nasution',
    gender: 'male',
    maritalStatus: 'married',
    age: 54,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'JAWA TIMUR',
    city: 'KOTA SURABAYA',
    salaryBucket: '> 100 Juta - 150 Juta',
    segment: 'Medium Value Customer',
    purchaseIntent: 'Family Protection',
    relationPolis: 'Orang tua kandung',
    productId: 1,
    productName: 'SIMAS JIWA LEGACY',
    totalPremi: 5896800,
    channel: 'Agency',
    transactionDate: '7/3/2020',
  },
  {
    id: 34,
    regSpaj: 'YKGICX7FNB',
    cif: '4JA8JZNL7K',
    policyNo: 'J8FQ6NT5QISQ',
    name: 'Yusuf Saragih',
    gender: 'male',
    maritalStatus: 'married',
    age: 42,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'JAWA TIMUR',
    city: 'KOTA SURABAYA',
    salaryBucket: '> 250 Juta - 300 Juta',
    segment: 'Medium Value Customer',
    purchaseIntent: 'Family Protection',
    relationPolis: 'Diri Sendiri',
    productId: 1,
    productName: 'SIMAS JIWA LEGACY',
    totalPremi: 2638710,
    channel: 'Agency',
    transactionDate: '7/30/2020',
  },
  {
    id: 35,
    regSpaj: '69AC9T6P07',
    cif: 'BHRQIJ4GYI',
    policyNo: '7WR4J759XOKL',
    name: 'Fajar Wijaya',
    gender: 'male',
    maritalStatus: 'married',
    age: 33,
    occupation: 'Karyawan Swasta',
    province: 'DKI JAKARTA',
    city: 'KOTA JAKARTA PUSAT',
    salaryBucket: '> 250 Juta - 300 Juta',
    segment: 'Medium Value Customer',
    purchaseIntent: 'Family Protection',
    relationPolis: 'Diri Sendiri',
    productId: 1,
    productName: 'SIMAS JIWA LEGACY',
    totalPremi: 3610000,
    channel: 'Agency',
    transactionDate: '12/22/2021',
  },
  {
    id: 36,
    regSpaj: '6WGL8I9AKF',
    cif: 'BOE0NLHG6H',
    policyNo: 'SW51AQH1UC3V',
    name: 'Yudi Sembiring',
    gender: 'male',
    maritalStatus: 'married',
    age: 57,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'JAWA TIMUR',
    city: 'KOTA SURABAYA',
    salaryBucket: '> 250 Juta - 300 Juta',
    segment: 'Medium Value Customer',
    purchaseIntent: 'Family Protection',
    relationPolis: 'Diri Sendiri',
    productId: 1,
    productName: 'SIMAS JIWA LEGACY',
    totalPremi: 6446790,
    channel: 'Agency',
    transactionDate: '11/10/2020',
  },
  {
    id: 37,
    regSpaj: '8MQ5S45NMT',
    cif: 'GQEIW2KJ0A',
    policyNo: 'RLS18FSRGF48',
    name: 'Ivan Sitorus',
    gender: 'male',
    maritalStatus: 'single',
    age: 21,
    occupation: 'Karyawan Swasta',
    province: 'KEPULAUAN RIAU',
    city: 'KOTA BATAM',
    salaryBucket: '> 500 Juta - 1 Milyar',
    segment: 'Medium Value Customer',
    purchaseIntent: 'Protection',
    relationPolis: 'Kerja/Majikan-Karyawan',
    productId: 7,
    productName: 'SIJATI',
    totalPremi: 2000000,
    channel: 'Agency',
    transactionDate: '4/4/2024',
  },
  {
    id: 38,
    regSpaj: 'VZ8KKD2D96',
    cif: 'CL8JB2MGMC',
    policyNo: 'V0V846AOES4J',
    name: 'Indah Samosir',
    gender: 'female',
    maritalStatus: 'married',
    age: 68,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'SUMATERA UTARA',
    city: 'ASAHAN',
    salaryBucket: '> 1 Milyar',
    segment: 'Top Customers',
    purchaseIntent: 'Investment',
    relationPolis: 'Orang tua kandung',
    productId: 3,
    productName: 'SIMAS SCHOLARSHIP PROTECTION',
    totalPremi: 250000000,
    channel: 'Bancassurance',
    transactionDate: '8/1/2025',
  },
  {
    id: 39,
    regSpaj: 'S0S3THZOUT',
    cif: 'PT1TM902AP',
    policyNo: '11H4IAUWKP5E',
    name: 'Ayu Tambunan',
    gender: 'female',
    maritalStatus: 'married',
    age: 32,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'JAWA TIMUR',
    city: 'KOTA SURABAYA',
    salaryBucket: '> 100 Juta - 150 Juta',
    segment: 'Top Customers',
    purchaseIntent: 'Protection',
    relationPolis: 'Diri Sendiri',
    productId: 1,
    productName: 'SIMAS JIWA LEGACY',
    totalPremi: 5590463,
    channel: 'Agency',
    transactionDate: '10/29/2025',
  },
  {
    id: 40,
    regSpaj: 'GFJHOU409Y',
    cif: 'C9PN1QRXG4',
    policyNo: 'U7O30YAJT4QG',
    name: 'Putri Budiman',
    gender: 'female',
    maritalStatus: 'widow',
    age: 40,
    occupation: 'Direktur',
    province: 'JAWA TENGAH',
    city: 'KOTA SEMARANG',
    salaryBucket: '> 100 Juta - 150 Juta',
    segment: 'Top Customers',
    purchaseIntent: 'Investment',
    relationPolis: 'Diri Sendiri',
    productId: 2,
    productName: 'SIPASTI',
    totalPremi: 15750000,
    channel: 'Bancassurance',
    transactionDate: '11/30/2023',
  },
  {
    id: 41,
    regSpaj: 'GSDJTCK00Z',
    cif: 'JJZ3F144WS',
    policyNo: 'GBRT5LAM7BU3',
    name: 'Mira Panjaitan',
    gender: 'female',
    maritalStatus: 'single',
    age: 44,
    occupation: 'Guru (Lainnya)',
    province: 'JAWA TIMUR',
    city: 'KOTA SURABAYA',
    salaryBucket: '> 100 Juta - 150 Juta',
    segment: 'Top Customers',
    purchaseIntent: 'Protection',
    relationPolis: 'Diri Sendiri',
    productId: 3,
    productName: 'SIMAS SCHOLARSHIP PROTECTION',
    totalPremi: 250000000,
    channel: 'Bancassurance',
    transactionDate: '7/17/2025',
  },
  {
    id: 42,
    regSpaj: 'FHYZ3K8XL7',
    cif: '7HWFTDO9KF',
    policyNo: 'WYA96EIZ0EKV',
    name: 'Mega Nasution',
    gender: 'female',
    maritalStatus: 'married',
    age: 66,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'JAWA BARAT',
    city: 'KOTA SUKABUMI',
    salaryBucket: '> 250 Juta - 300 Juta',
    segment: 'Top Customers',
    purchaseIntent: 'Protection',
    relationPolis: 'Orang tua kandung',
    productId: 3,
    productName: 'SIMAS SCHOLARSHIP PROTECTION',
    totalPremi: 500000000,
    channel: 'Bancassurance',
    transactionDate: '8/15/2025',
  },
  {
    id: 43,
    regSpaj: 'JP192IUUFL',
    cif: 'YS73VLZRAP',
    policyNo: 'G33SUB8WLFYA',
    name: 'Ika Purnama',
    gender: 'female',
    maritalStatus: 'married',
    age: 64,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'RIAU',
    city: 'KOTA PEKAN BARU',
    salaryBucket: '> 500 Juta - 1 Milyar',
    segment: 'Top Customers',
    purchaseIntent: 'Investment',
    relationPolis: 'Diri Sendiri',
    productId: 3,
    productName: 'SIMAS SCHOLARSHIP PROTECTION',
    totalPremi: 300000000,
    channel: 'Bancassurance',
    transactionDate: '7/10/2025',
  },
  {
    id: 44,
    regSpaj: 'LXSY4VY32I',
    cif: '4TB76GIN1X',
    policyNo: 'IVW5HX2S2MNN',
    name: 'Nanda Santoso',
    gender: 'male',
    maritalStatus: 'married',
    age: 68,
    occupation: 'Karyawan Swasta',
    province: 'SUMATERA BARAT',
    city: 'KOTA PADANG',
    salaryBucket: '> 500 Juta - 1 Milyar',
    segment: 'Top Customers',
    purchaseIntent: 'Investment',
    relationPolis: 'Suami/Istri',
    productId: 3,
    productName: 'SIMAS SCHOLARSHIP PROTECTION',
    totalPremi: 1000000000,
    channel: 'Bancassurance',
    transactionDate: '9/12/2025',
  },
  {
    id: 45,
    regSpaj: 'H7PPCADUVL',
    cif: 'S667A0EFWJ',
    policyNo: 'TO9SEBS7IN20',
    name: 'Arif Purba',
    gender: 'male',
    maritalStatus: 'married',
    age: 37,
    occupation: 'Pemuka Agama',
    province: 'DKI JAKARTA',
    city: 'KOTA JAKARTA PUSAT',
    salaryBucket: '0 - 50 Juta',
    segment: 'Top Customers',
    purchaseIntent: 'Protection',
    relationPolis: 'Diri Sendiri',
    productId: 3,
    productName: 'SIMAS SCHOLARSHIP PROTECTION',
    totalPremi: 120000000,
    channel: 'Agency',
    transactionDate: '7/7/2025',
  },
  {
    id: 46,
    regSpaj: 'TEKT3DHERH',
    cif: '1ZZJ85G1BA',
    policyNo: '2DG74R1YCC7Z',
    name: 'Andi Simanjuntak',
    gender: 'male',
    maritalStatus: 'married',
    age: 62,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'KALIMANTAN TIMUR',
    city: 'KOTA SAMARINDA',
    salaryBucket: '> 1 Milyar',
    segment: 'Top Customers',
    purchaseIntent: 'Protection',
    relationPolis: 'Diri Sendiri',
    productId: 3,
    productName: 'SIMAS SCHOLARSHIP PROTECTION',
    totalPremi: 1000000000,
    channel: 'Bancassurance',
    transactionDate: '8/6/2025',
  },
  {
    id: 47,
    regSpaj: 'CPV4H1RZF1',
    cif: 'A9R0UAPRJ2',
    policyNo: 'W8TJG9IY19ON',
    name: 'Ryan Siregar',
    gender: 'male',
    maritalStatus: 'married',
    age: 36,
    occupation: 'Karyawan Swasta',
    province: 'JAWA TIMUR',
    city: 'KOTA SURABAYA',
    salaryBucket: '> 100 Juta - 150 Juta',
    segment: 'Top Customers',
    purchaseIntent: 'Family Protection',
    relationPolis: 'Diri Sendiri',
    productId: 1,
    productName: 'SIMAS JIWA LEGACY',
    totalPremi: 10193500,
    channel: 'Agency',
    transactionDate: '9/30/2020',
  },
  {
    id: 48,
    regSpaj: 'BXMMNR1V1Z',
    cif: 'D1CECZW3YN',
    policyNo: 'M9OZW85CUEY6',
    name: 'Nico Prasetyo',
    gender: 'male',
    maritalStatus: 'single',
    age: 36,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'JAWA TIMUR',
    city: 'KOTA SURABAYA',
    salaryBucket: '0 - 50 Juta',
    segment: 'Top Customers',
    purchaseIntent: 'Investment',
    relationPolis: 'Diri Sendiri',
    productId: 1,
    productName: 'SIMAS JIWA LEGACY',
    totalPremi: 15901920,
    channel: 'Agency',
    transactionDate: '9/26/2019',
  },
  {
    id: 49,
    regSpaj: '7WGXXASHVF',
    cif: 'YDC2F96KCN',
    policyNo: 'LPR1QUW10VXC',
    name: 'Zaki Purnama',
    gender: 'male',
    maritalStatus: 'married',
    age: 53,
    occupation: 'Wiraswasta/Wirausaha',
    province: 'JAWA TIMUR',
    city: 'KOTA SURABAYA',
    salaryBucket: '0 - 50 Juta',
    segment: 'Top Customers',
    purchaseIntent: 'Family Protection',
    relationPolis: 'Diri Sendiri',
    productId: 1,
    productName: 'SIMAS JIWA LEGACY',
    totalPremi: 6040125,
    channel: 'Agency',
    transactionDate: '9/24/2020',
  },
];